export const LicenseService = {
	async getListOfLicenses() {
		const url = 'http://localhost:8080/license/list?page=0&perPage=20';
		try {
			const response = await fetch(url);

			if (!response.ok) {
				throw new Error('Network response was not ok');
			}
			const data = await response.json();
			console.log('Log the fetched data:', data); // Log the fetched data
			return data;
		} catch (error) {
			console.error('There was a problem with the fetch operation:', error);
		}
	},

	getMockedLicenseData() {
		return [
			// ID is not presented in the table right now.

			{
				id: '1000',
				wbs: 'f230fh0g3',
				name: 'Bamboo Watch',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183420',
				quantity: 24,
				status: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1001',
				wbs: 'nvklal433',
				name: 'Black Watch',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183421',
				quantity: 61,
				status: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1002',
				wbs: 'zz21cz3c1',
				name: 'Blue Band',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183422',
				quantity: 2,
				status: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1003',
				wbs: '244wgerg2',
				name: 'Blue T-Shirt',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183423',
				quantity: 25,
				status: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1004',
				wbs: 'h456wer53',
				name: 'Bracelet',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183420',
				quantity: 73,
				status: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1005',
				wbs: 'av2231fwg',
				name: 'Brown Purse',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183421',
				quantity: 0,
				status: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1006',
				wbs: 'bib36pfvm',
				name: 'Chakra Bracelet',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183424',
				quantity: 5,
				status: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1007',
				wbs: 'mbvjkgip5',
				name: 'Galaxy Earrings',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183425',
				quantity: 23,
				status: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1008',
				wbs: 'vbb124btr',
				name: 'Game Controller',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183426',
				quantity: 2,
				status: 'EXPIRING SOON',
				expiryDate: '24-04-2024',
			},
			{
				id: '1009',
				wbs: 'cm230f032',
				name: 'Gaming Set',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183427',
				quantity: 63,
				status: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1010',
				wbs: 'plb34234v',
				name: 'Gold Phone Case',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183428',
				quantity: 0,
				status: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1011',
				wbs: '4920nnc2d',
				name: 'Green Earbuds',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183429',
				quantity: 23,
				status: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1012',
				wbs: '250vm23cc',
				name: 'Green T-Shirt',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183430',
				quantity: 74,
				status: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1013',
				wbs: 'fldsmn31b',
				name: 'Grey T-Shirt',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183431',
				quantity: 0,
				status: 'EXPIRED',
				expiryDate: '23-03-2023',
			},
			{
				id: '1014',
				wbs: 'waas1x2as',
				name: 'Headphones',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				totalPrice: 65,
				unitPrice: 65,
				po: 'PR3183432',
				quantity: 8,
				status: 'EXPIRING SOON',
				expiryDate: '25-10-2025',
			},
		];
	},
};
