export const LicenseService = {
	getLicensesData() {
		return [
			// ID is not presented in the table right now.

			{
				id: '1000',
				wbs: 'f230fh0g3',
				name: 'Bamboo Watch',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 65,
				po: 'PR3183420',
				quantity: 24,
				licenseStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1001',
				wbs: 'nvklal433',
				name: 'Black Watch',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 72,
				po: 'PR3183421',
				quantity: 61,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1002',
				wbs: 'zz21cz3c1',
				name: 'Blue Band',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 79,
				po: 'PR3183422',
				quantity: 2,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1003',
				wbs: '244wgerg2',
				name: 'Blue T-Shirt',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 29,
				po: 'PR3183423',
				quantity: 25,
				licenseStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1004',
				wbs: 'h456wer53',
				name: 'Bracelet',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 15,
				po: 'PR3183420',
				quantity: 73,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1005',
				wbs: 'av2231fwg',
				name: 'Brown Purse',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 120,
				po: 'PR3183421',
				quantity: 0,
				licenseStatus: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1006',
				wbs: 'bib36pfvm',
				name: 'Chakra Bracelet',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 32,
				po: 'PR3183424',
				quantity: 5,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1007',
				wbs: 'mbvjkgip5',
				name: 'Galaxy Earrings',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 34,
				po: 'PR3183425',
				quantity: 23,
				licenseStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1008',
				wbs: 'vbb124btr',
				name: 'Game Controller',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 99,
				po: 'PR3183426',
				quantity: 2,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '24-04-2024',
			},
			{
				id: '1009',
				wbs: 'cm230f032',
				name: 'Gaming Set',
				note: 'Product note',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				price: 299,
				po: 'PR3183427',
				quantity: 63,
				licenseStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1010',
				wbs: 'plb34234v',
				name: 'Gold Phone Case',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 24,
				po: 'PR3183428',
				quantity: 0,
				licenseStatus: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1011',
				wbs: '4920nnc2d',
				name: 'Green Earbuds',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 89,
				po: 'PR3183429',
				quantity: 23,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1012',
				wbs: '250vm23cc',
				name: 'Green T-Shirt',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 49,
				po: 'PR3183430',
				quantity: 74,
				licenseStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1013',
				wbs: 'fldsmn31b',
				name: 'Grey T-Shirt',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 48,
				po: 'PR3183431',
				quantity: 0,
				licenseStatus: 'EXPIRED',
				expiryDate: '23-03-2023',
			},
			{
				id: '1014',
				wbs: 'waas1x2as',
				name: 'Headphones',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 175,
				po: 'PR3183432',
				quantity: 8,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '25-10-2025',
			},
			{
				id: '1015',
				wbs: 'vb34btbg5',
				name: 'Light Green T-Shirt',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 49,
				po: 'PR3183433',
				quantity: 34,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1016',
				wbs: 'k8l6j58jl',
				name: 'Lime Band',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 79,
				po: 'PR3183475',
				quantity: 12,
				licenseStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1017',
				wbs: 'v435nn85n',
				name: 'Mini Speakers',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 85,
				po: 'PR3183434',
				quantity: 42,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1018',
				wbs: '09zx9c0zc',
				name: 'Painted Phone Case',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 56,
				po: 'PR3183435',
				quantity: 41,
				licenseStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1019',
				wbs: 'mnb5mb2m5',
				name: 'Pink Band',
				note: 'Product note',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				price: 79,
				po: 'PR3183436',
				quantity: 63,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1020',
				wbs: 'r23fwf2w3',
				name: 'Pink Purse',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 110,
				po: 'PR3183437',
				quantity: 0,
				licenseStatus: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1021',
				wbs: 'pxpzczo23',
				name: 'Purple Band',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 79,
				po: 'PR3183438',
				quantity: 6,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1022',
				wbs: '2c42cb5cb',
				name: 'Purple Gemstone Necklace',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 45,
				po: 'PR3183439',
				quantity: 62,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1023',
				wbs: '5k43kkk23',
				name: 'Purple T-Shirt',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 49,
				po: 'PR3183440',
				quantity: 2,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '25-10-2025',
			},
			{
				id: '1024',
				wbs: 'lm2tny2k4',
				name: 'Shoes',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 64,
				po: 'PR3183442',
				quantity: 0,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1025',
				wbs: 'nbm5mv45n',
				name: 'Sneakers',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 78,
				po: 'PR3183451',
				quantity: 52,
				licenseStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1026',
				wbs: 'zx23zc42c',
				name: 'Teal T-Shirt',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 49,
				po: 'PR3183458',
				quantity: 3,
				licenseStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1027',
				wbs: 'acvx872gc',
				name: 'Yellow Earbuds',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 89,
				po: 'PR3183465',
				quantity: 35,
				licenseStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1028',
				wbs: 'tx125ck42',
				name: 'Yoga Mat',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 20,
				po: 'PR3183468',
				quantity: 15,
				licenseStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1029',
				wbs: 'gwuby345v',
				name: 'Yoga Set',
				note: 'Product note',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				price: 20,
				po: 'PR3183473',
				quantity: 25,
				licenseStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
		];
	},

	getLicensesMini() {
		return Promise.resolve(this.getLicensesData().slice(0, 5));
	},

	getLicensesSmall() {
		return Promise.resolve(this.getLicensesData().slice(0, 10));
	},

	getLicenses() {
		return Promise.resolve(this.getLicensesData());
	},
};
