export const LicenseService = {
	getLicensesData() {
		return [
			// Image, category and price are not presented in the table right now

			{
				id: '1000',
				code: 'f230fh0g3',
				name: 'Bamboo Watch',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'bamboo-watch.jpg',
				price: 65,
				category: 'Artists',
				quantity: 24,
				inventoryStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1001',
				code: 'nvklal433',
				name: 'Black Watch',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'black-watch.jpg',
				price: 72,
				category: 'Artists',
				quantity: 61,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1002',
				code: 'zz21cz3c1',
				name: 'Blue Band',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'blue-band.jpg',
				price: 79,
				category: 'Fitness',
				quantity: 2,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1003',
				code: '244wgerg2',
				name: 'Blue T-Shirt',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'blue-t-shirt.jpg',
				price: 29,
				category: 'Renderfarm',
				quantity: 25,
				inventoryStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1004',
				code: 'h456wer53',
				name: 'Bracelet',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'bracelet.jpg',
				price: 15,
				category: 'Artists',
				quantity: 73,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1005',
				code: 'av2231fwg',
				name: 'Brown Purse',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'brown-purse.jpg',
				price: 120,
				category: 'Artists',
				quantity: 0,
				inventoryStatus: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1006',
				code: 'bib36pfvm',
				name: 'Chakra Bracelet',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'chakra-bracelet.jpg',
				price: 32,
				category: 'Artists',
				quantity: 5,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1007',
				code: 'mbvjkgip5',
				name: 'Galaxy Earrings',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'galaxy-earrings.jpg',
				price: 34,
				category: 'Artists',
				quantity: 23,
				inventoryStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1008',
				code: 'vbb124btr',
				name: 'Game Controller',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'game-controller.jpg',
				price: 99,
				category: 'Monitoring',
				quantity: 2,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '24-04-2024',
			},
			{
				id: '1009',
				code: 'cm230f032',
				name: 'Gaming Set',
				notes: 'Product notes',
				vendor: 'DVEAS',
				manufacturer: 'AUTODESK',
				image: 'gaming-set.jpg',
				price: 299,
				category: 'Monitoring',
				quantity: 63,
				inventoryStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1010',
				code: 'plb34234v',
				name: 'Gold Phone Case',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'gold-phone-case.jpg',
				price: 24,
				category: 'Artists',
				quantity: 0,
				inventoryStatus: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1011',
				code: '4920nnc2d',
				name: 'Green Earbuds',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'green-earbuds.jpg',
				price: 89,
				category: 'Monitoring',
				quantity: 23,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1012',
				code: '250vm23cc',
				name: 'Green T-Shirt',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'green-t-shirt.jpg',
				price: 49,
				category: 'Renderfarm',
				quantity: 74,
				inventoryStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1013',
				code: 'fldsmn31b',
				name: 'Grey T-Shirt',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'grey-t-shirt.jpg',
				price: 48,
				category: 'Renderfarm',
				quantity: 0,
				inventoryStatus: 'EXPIRED',
				expiryDate: '23-03-2023',
			},
			{
				id: '1014',
				code: 'waas1x2as',
				name: 'Headphones',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'headphones.jpg',
				price: 175,
				category: 'Monitoring',
				quantity: 8,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '25-10-2025',
			},
			{
				id: '1015',
				code: 'vb34btbg5',
				name: 'Light Green T-Shirt',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'light-green-t-shirt.jpg',
				price: 49,
				category: 'Renderfarm',
				quantity: 34,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1016',
				code: 'k8l6j58jl',
				name: 'Lime Band',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'lime-band.jpg',
				price: 79,
				category: 'Fitness',
				quantity: 12,
				inventoryStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1017',
				code: 'v435nn85n',
				name: 'Mini Speakers',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'mini-speakers.jpg',
				price: 85,
				category: 'Renderfarm',
				quantity: 42,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1018',
				code: '09zx9c0zc',
				name: 'Painted Phone Case',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'painted-phone-case.jpg',
				price: 56,
				category: 'Artists',
				quantity: 41,
				inventoryStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1019',
				code: 'mnb5mb2m5',
				name: 'Pink Band',
				notes: 'Product notes',
				vendor: 'SIDEFX',
				manufacturer: 'SIDEFX',
				image: 'pink-band.jpg',
				price: 79,
				category: 'Fitness',
				quantity: 63,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1020',
				code: 'r23fwf2w3',
				name: 'Pink Purse',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'pink-purse.jpg',
				price: 110,
				category: 'Artists',
				quantity: 0,
				inventoryStatus: 'EXPIRED',
				expiryDate: '24-04-2024',
			},
			{
				id: '1021',
				code: 'pxpzczo23',
				name: 'Purple Band',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'purple-band.jpg',
				price: 79,
				category: 'Fitness',
				quantity: 6,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1022',
				code: '2c42cb5cb',
				name: 'Purple Gemstone Necklace',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'purple-gemstone-necklace.jpg',
				price: 45,
				category: 'Artists',
				quantity: 62,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1023',
				code: '5k43kkk23',
				name: 'Purple T-Shirt',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'purple-t-shirt.jpg',
				price: 49,
				category: 'Renderfarm',
				quantity: 2,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '25-10-2025',
			},
			{
				id: '1024',
				code: 'lm2tny2k4',
				name: 'Shoes',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'shoes.jpg',
				price: 64,
				category: 'Renderfarm',
				quantity: 0,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1025',
				code: 'nbm5mv45n',
				name: 'Sneakers',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'sneakers.jpg',
				price: 78,
				category: 'Renderfarm',
				quantity: 52,
				inventoryStatus: 'VALID',
				expiryDate: '24-04-2024',
			},
			{
				id: '1026',
				code: 'zx23zc42c',
				name: 'Teal T-Shirt',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'teal-t-shirt.jpg',
				price: 49,
				category: 'Renderfarm',
				quantity: 3,
				inventoryStatus: 'EXPIRING SOON',
				expiryDate: '23-03-2023',
			},
			{
				id: '1027',
				code: 'acvx872gc',
				name: 'Yellow Earbuds',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'yellow-earbuds.jpg',
				price: 89,
				category: 'Monitoring',
				quantity: 35,
				inventoryStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
			{
				id: '1028',
				code: 'tx125ck42',
				name: 'Yoga Mat',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'yoga-mat.jpg',
				price: 20,
				category: 'Fitness',
				quantity: 15,
				inventoryStatus: 'VALID',
				expiryDate: '25-10-2025',
			},
			{
				id: '1029',
				code: 'gwuby345v',
				name: 'Yoga Set',
				notes: 'Product notes',
				vendor: 'FOUNDRY',
				manufacturer: 'FOUNDRY',
				image: 'yoga-set.jpg',
				price: 20,
				category: 'Fitness',
				quantity: 25,
				inventoryStatus: 'VALID',
				expiryDate: '23-03-2023',
			},
		];
	},

	getLicensesMini() {
		return Promise.resolve(this.getLicensesData().slice(0, 5));
	},

	getLicensesSmall() {
		return Promise.resolve(this.getLicensesData().slice(0, 10));
	},

	getLicenses() {
		return Promise.resolve(this.getLicensesData());
	},
};
